lib/App/cpm.pm
lib/App/cpm/Worker/Installer.pm
script/cpm
xt/10_basic.t

Addresses @ichesnokov's #14 
This PR introduces `--test` option, which makes cpm run tests of cpan modules.
Example:
```
> perl -Ilib script/cpm install -v --test Plack
48768 DONE resolve   (0.082sec) Plack -> Plack-1.0039
48770 DONE fetch     (0.833sec) Plack-1.0039
48769 DONE resolve   (0.114sec) File::ShareDir::Install -> File-ShareDir-Install-0.10
48772 DONE fetch     (0.398sec) File-ShareDir-Install-0.10
48771 DONE configure (0.190sec) File-ShareDir-Install-0.10
48768 DONE install   (1.949sec) File-ShareDir-Install-0.10
48770 DONE configure (0.358sec) Plack-1.0039
48769 DONE resolve   (0.201sec) Filesys::Notify::Simple -> Filesys-Notify-Simple-0.12
48768 DONE resolve   (0.201sec) Try::Tiny -> Try-Tiny-0.24
48772 DONE resolve   (0.316sec) HTTP::Body -> HTTP-Body-1.22
48769 DONE …
```

add --test option

---

.travis.yml
META.json
Makefile.PL
cpanfile
lib/App/cpm.pm
lib/App/cpm/Master.pm
script/cpm
xt/11_target_perl.t
xt/CLI.pm

retake #9 
Introduce --target-perl option.
Eg:
```
$ perl -v
This is perl 5, version 22, subversion 1 (v5.22.1) built for darwin-2level
$ cat cpanfile
requires 'HTTP::Tinyish';
$ cpm install --target-perl 5.8.5
Loading modules from cpanfile...
DONE install HTTP-Tiny-0.056
DONE install IPC-Run3-0.048
DONE install parent-0.234 <==== parent module is not core in 5.8.5, so is installed
DONE install File-Which-1.19
DONE install HTTP-Tinyish-0.07
5 distributions installed.
```
This option may be useful when you generate a fatpacked script which supports old perls.

introduce --target-perl option

---

lib/App/cpm.pm
lib/App/cpm/Distribution.pm
lib/App/cpm/Master.pm
xt/14_perl_req.t
xt/CLI.pm

Now cpm correctly handles `perl` requirements.
Eg:
```
> cpm install --target-perl 5.8.5 Mojolicious
FAIL Mojolicious-6.50 requires perl 5.010001
...
> cat cpanfile
requires "perl", "5.30.0";
requires "Plack";
> cpm install
Loading modules from cpanfile...
cpanfile requires perl 5.30.0
```

handle perl requirement

---

lib/App/cpm.pm
lib/App/cpm/Worker/Installer.pm

Now cpm save dists in ~/perl-cpm/cache:
```
> find ~/.perl-cpm/cache -type f
/Users/skaji/.perl-cpm/cache/authors/id/A/AD/ADAMK/Class-Inspector-1.28.tar.gz
/Users/skaji/.perl-cpm/cache/authors/id/A/AD/ADAMK/Params-Util-1.07.tar.gz
/Users/skaji/.perl-cpm/cache/authors/id/A/AR/ARISTOTLE/Hash-MultiValue-0.16.tar.gz
/Users/skaji/.perl-cpm/cache/authors/id/C/CJ/CJM/IO-HTML-1.001.tar.gz
/Users/skaji/.perl-cpm/cache/authors/id/C/CO/CORION/parent-0.234.tar.gz
/Users/skaji/.perl-cpm/cache/authors/id/D/DA/DAGOLDEN/File-pushd-1.009.tar.gz
...
```
And the cache exists, cpm use it instead of fetching it from CPAN.
This makes cpm even faster!
Without cache
```
> perl -Ilib script/cpm install Plack
perl -Ilib script/cpm install Plack  18.85s user 5.00s system 210% cpu 11.334 total
```
With cache
```
> …
```

save distfile and use it if it exists

---

.travis.yml
META.json
cpanfile
lib/App/cpm.pm
lib/App/cpm/Master.pm
lib/App/cpm/Worker.pm
lib/App/cpm/Worker/Resolver.pm
lib/App/cpm/Worker/Resolver/MetaDB.pm
lib/App/cpm/Worker/Resolver/Snapshot.pm
xt/03_resolver.t
xt/15_snapshot.t

Let's introduce App::cpm::Worker::Resolver::* classes.
There are several ways to resolve "where the module is":
* http://cpanmetadb.plackperl.org/
* http://some-cpan-mirror/modules/02packages.details.txt.gz
* /local/path/to/02packages.details.txt.gz
* metacapn api
* cpanfile
* cpanfile.snapshot
* custom api (such as https://stratopan.com/)
And people sometimes want to multiplex these sources in some ways.
This PR is a beginning of supporting these.

Introduce  App::cpm::Worker::Resolver::*

---

lib/App/cpm.pm
lib/App/cpm/Distribution.pm
lib/App/cpm/Logger/File.pm
lib/App/cpm/Master.pm
lib/App/cpm/Worker.pm
lib/App/cpm/Worker/Installer.pm
lib/App/cpm/Worker/Installer/Menlo.pm
lib/App/cpm/Worker/Resolver.pm
xt/02_installer.t

fix #51 
As mentioned in README, cpm's log is really messy, so it is difficult to find out the reason of failure from the log file.
Now cpm uses App::cpm::Logger::File to emit log, which hopefully helps you.
```
> cpm install Plack
...
> less ~/.perl-cpm/build.log
2016-12-10T11:08:16,86583| You have make /usr/bin/make
2016-12-10T11:08:16,86583| You have LWP: 6.15
2016-12-10T11:08:16,86583| You have LWP::Protocol::https: 6.06
2016-12-10T11:08:16,86583| You have /usr/local/opt/gnu-tar/libexec/gnubin/tar: tar (GNU tar) 1.29
2016-12-10T11:08:16,86583| Copyright (C) 2015 Free Software Foundation, Inc.
2016-12-10T11:08:16,86583| License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
2016-12-10T11:08:16,86583| This is free software: you are free to change and redistribute …
```

use App::cpm::Logger::File

---

lib/App/cpm.pm
lib/App/cpm/Distribution.pm
lib/App/cpm/Master.pm
lib/App/cpm/Resolver/02Packages.pm
lib/App/cpm/Resolver/Cascade.pm
lib/App/cpm/Resolver/MetaCPAN.pm
lib/App/cpm/Resolver/MetaDB.pm
lib/App/cpm/Resolver/Snapshot.pm
lib/App/cpm/Worker/Installer.pm
lib/App/cpm/version.pm
xt/01_installer.t
xt/23_up_to_date.t

before
```
> perl -Ilib script/cpm install App::ChangeShebang@0.06
DONE install App-ChangeShebang-0.06
1 distribution installed.
> perl -Ilib script/cpm install App::ChangeShebang@0.05
DONE install App::ChangeShebang is up to date. (0.05)
0 distribution installed.
```
Now
```
> perl -Ilib script/cpm install App::ChangeShebang@0.06
DONE install App-ChangeShebang-0.06
1 distribution installed.
> perl -Ilib script/cpm install App::ChangeShebang@0.05
DONE install App-ChangeShebang-0.05
1 distribution installed.
```
Note that this PR also contains a change for App::cpm::Resolver interface.
Now App::cpm::Resolver->resolve will be called with
```
$job = {
package => "Plack",
version_range => "< 2.000, >= 1.000", # previously "version" key name
}
```

fix up-to-date handling

---

.travis.yml
lib/App/cpm.pm
lib/App/cpm/Master.pm
xt/24_core.t

fix #42 
cpm was checking whether a module is installed or not by:
```perl
sub installed {
my ($self, $package, $version) = @_;
return 1 if $package is core;
return 1 if $package is in INC;
return 0;
}
```
But some modules, which must be core, are not present. (Then what "core" means:/)
Now cpm do not assume core modules are always present,
so that it always checks modules are in INC or not.

do not assume core modules are always present

---

lib/App/cpm.pm
lib/App/cpm/Distribution.pm
lib/App/cpm/Job.pm
lib/App/cpm/Logger.pm
lib/App/cpm/Master.pm
lib/App/cpm/Worker.pm
lib/App/cpm/Worker/Installer.pm
script/cpm
xt/01_installer.t
xt/30_prebuilt.t

Now cpm keeps the each builds of distributions in your home directory.
Then `cpm install` will use these prebuilt distributions.
That is, if prebuilts are available, cpm never build distributions again, just copy prebuilts into an appropriate directory.
This is (of course!) inspired by Carmel.
[![asciicast](https://asciinema.org/a/125492.png)](https://asciinema.org/a/125492?autoplay=1)

keep prebuilts and use them later

---

lib/App/cpm.pm
lib/App/cpm/CircularDependency.pm
lib/App/cpm/Master.pm
xt/31_circular_dep.t

Fix #69 
```
❯ export PERL_CPM_PREBUILT=1 OPENSSL_INCLUDE=/usr/local/opt/openssl/include OPENSSL_LIB=/usr/local/opt/openssl/lib
❯ perl -Ilib script/cpm install Net::HTTP@6.11
DONE install Socket6-0.28 (using prebuilt)
DONE install Mozilla-CA-20160104 (using prebuilt)
DONE install Module-Build-0.4224 (using prebuilt)
DONE install IO-Socket-INET6-2.72 (using prebuilt)
DONE install Path-Class-0.37 (using prebuilt)
DONE install Try-Tiny-0.28 (using prebuilt)
DONE install URI-1.71 (using prebuilt)
DONE install Net-SSLeay-1.81 (using prebuilt)
DONE install IO-Socket-SSL-2.049 (using prebuilt)
DONE install LWP-MediaTypes-6.02 (using prebuilt)
DONE install WWW-RobotRules-6.02 (using prebuilt)
DONE install Encode-Locale-1.05 (using prebuilt)
DONE install File-Listing-6.04 (using prebuilt)
DONE …
```

detect circular dependencies

---

lib/App/cpm/Logger.pm

re: https://github.com/skaji/cpm/pull/98#issuecomment-313968903
With this module, you can colorize log under Win32.

use Win32::Console::ANSI (if available) to support color option under Win32

---

META.json
cpanfile
lib/App/cpm.pm

This reduces the size of fatpacked cpm.
before
```
❯ ls -al cpm
-rw-r--r-- 1 skaji staff 870043 Dec 30 02:50 cpm
```
after
```
❯ ls -al cpm
-rw-r--r-- 1 skaji staff 638756 Dec 30 02:55 cpm
```

use Pod::Text instead of Pod::Usage

---

lib/App/cpm/CLI.pm
lib/App/cpm/Master.pm
xt/21_resolver_option.t
xt/lib/CLI.pm

Fix #143 
When `cpm install -L Module`,
if some dependencies are in core INC, but not listed in Module::CoreList,
then we should treat them as not being installed.
This also follows the cpanminus behavior.
See https://github.com/miyagawa/cpanminus/blob/7b574ede70cebce3709743ec1727f90d745e8580/Menlo-Legacy/lib/Menlo/CLI/Compat.pm#L1783-L1786

check if dependencies in core INC are actually core

---

lib/App/cpm/Installer/Unpacker.pm

When tar is run as root it attempts to preserve user & group ownership by
default. If the uid and gid don't exist this can cause tar to fail. A good
example is Number-Compare 0.03, which have uid 831580115 and gid
755412454. Attempting to untar this as root will fail.
While normally we don't expect to be run as root, this is quite common when
running Docker, which in turn is used by many CI environments, including
CircleCI.

call tar with --no-same-owner

---

lib/App/cpm/Installer/Unpacker.pm

```
===> C:\windows\system32\tar.EXE --version
bsdtar 3.3.2 - libarchive 3.3.2 zlib/1.2.5.f-ipp
===> C:\windows\system32\tar.EXE --force-local -zxf D:\a\perl-github-actions-sample\perl-github-actions-sample\App-tldr-0.10.tar.gz -o
tar.EXE: Option --force-local is not supported
Usage:
List:    tar.EXE -tf <archive-filename>
Extract: tar.EXE -xf <archive-filename>
Create:  tar.EXE -cf <archive-filename> [filenames...]
Help:    tar.EXE --help
===> $? = 256
```

do not use --force-local for bsdtar

---

lib/App/cpm/Master.pm
xt/36_fail.t

Fix #184 
```
❯ perl -Ilib script/cpm install --test CPAN::Test::Dummy::Perl5::Build::DepeFails
FAIL install CPAN-Test-Dummy-Perl5-Build-Fails-1.03
FAIL install CPAN-Test-Dummy-Perl5-Build-DepeFails-1.02
FAIL install CPAN-Test-Dummy-Perl5-Build-Fails-1.03
0 distribution installed.
See /Users/skaji/.perl-cpm/build.log for details.
❯ tail /Users/skaji/.perl-cpm/build.log
2020-11-06T00:29:07,45197,CPAN-Test-Dummy-Perl5-Build-Fails-1.03| t/00_load.t (Wstat: 0 Tests: 2 Failed: 1)
2020-11-06T00:29:07,45197,CPAN-Test-Dummy-Perl5-Build-Fails-1.03|   Failed test:  2
2020-11-06T00:29:07,45197,CPAN-Test-Dummy-Perl5-Build-Fails-1.03| Files=1, Tests=2,  0 wallclock secs ( 0.01 usr  0.01 sys +  0.00 cusr  0.01 csys =  0.03 CPU)
2020-11-06T00:29:07,45197,CPAN-Test-Dummy-Perl5-Build-Fails-1.03| Result: …
```

dump direct cause of the failure to build log in the end

---

lib/App/cpm/CLI.pm

resolve #187 
it shows like:
```
$ perl -Mlib=local/lib/perl5 -Ilib -E 'use App::cpm::CLI; App::cpm::CLI->cmd_version'
cpm 0.994 (-e)
perl version v5.32.0 (/usr/local/Cellar/perl/5.32.0/bin/perl)
%Config:
archname=darwin-thread-multi-2level
installsitelib=/usr/local/Cellar/perl/5.32.0/lib/perl5/site_perl/5.32.0
installsitebin=/usr/local/Cellar/perl/5.32.0/bin
installman1dir=/usr/local/Cellar/perl/5.32.0/share/man/man1
installman3dir=/usr/local/Cellar/perl/5.32.0/share/man/man3
sitearchexp=/usr/local/Cellar/perl/5.32.0/lib/perl5/site_perl/5.32.0/darwin-thread-multi-2level
sitelibexp=/usr/local/Cellar/perl/5.32.0/lib/perl5/site_perl/5.32.0
archlibexp=/usr/local/Cellar/perl/5.32.0/lib/perl5/5.32.0/darwin-thread-multi-2level
privlibexp=/usr/local/Cellar/perl/5.32.0/lib/perl5/5.32.0
%ENV: …
```

show more info in cpm --version

---

META.json
cpanfile
lib/App/cpm/CLI.pm
lib/App/cpm/file.pm
xt/19_cpmfile.t

This PR introduces cpmfile (cpm.yml), which is a new file format describing dependencies.
An example of cpmfile is:
```yaml
prereqs:
develop:
requires:
Archive::Tar:
Archive::Zip: { version: '1.68' }
CPAN::Mirror::Tiny: { version: '0.20' }
Capture::Tiny:
Path::Tiny:
Test::More: { version: '0.98' }
runtime:
recommends:
Carton:
IO::Uncompress::Gunzip:
requires:
CPAN::Common::Index:
CPAN::DistnameInfo:
CPAN::Meta:
CPAN::Meta::Requirements: { version: '2.130' }
CPAN::Meta::YAML:
Class::Tiny:
Command::Runner: { version: '0.100' }
ExtUtils::Install: { version: '2.20' }
```
Currently cpmfile is almost the same as "prereqs" in META.json/yml.
More interesting features will follow, I hope. eg: https://github.com/skaji/cpm/pull/119

introduce cpmfile

---

lib/App/cpm/CLI.pm
lib/App/cpm/Resolver/Custom.pm
xt/17_cpanfile.t
xt/19_cpmfile.t

Now cpm supports dist/url/git syntax in cpmfile (cpm.yml):
```yaml
prereqs:
runtime:
requires:
Hash::MultiValue: { dist: "MIYAGAWA/Hash-MultiValue-0.15.tar.gz" }
Try::Tiny: { url: "http://backpan.perl.org/authors/id/E/ET/ETHER/Try-Tiny-0.28.tar.gz" }
App::ChangeShebang: { git: 'https://github.com/skaji/change-shebang', ref: '0.05' }
```

support dist/url/git syntax in cpmfile

---

lib/App/cpm/Worker/Installer/Menlo.pm

Currenly, cpm or cpanminus does not look at HTTP status code when fetching tarballs.
https://github.com/miyagawa/cpanminus/blob/92b34956c52e61c09ae11010f98061730e30fef4/Menlo-Legacy/lib/Menlo/CLI/Compat.pm#L1424-L1425
This PR changes it, and emits HTTP status code to build.log:
```
❯ perl -Ilib script/cpm install --no-prebuilt --home $PWD/home --resolver metadb,https://cpanmetadb.plackperl.org/v1.0/,https://151.101.110.217/  App::cpm
FAIL install App-cpm-0.997006
0 distribution installed.
See /Users/skaji/src/github.com/skaji/cpm/home/build.log for details.
You may want to execute cpm with --show-build-log-on-failure,
so that the build.log is automatically dumped on failure.
❯ cat $PWD/home/build.log
...
2021-09-23T20:55:55,44727,App::cpm| Resolved App::cpm (0) -> …
```

check http status code when fetching tarballs

---

.github/workflows/test.yml
README.md
lib/App/cpm/Tutorial.pm

On April 29th, git.io is going to stop redirecting.
https://github.blog/changelog/2022-04-25-git-io-deprecation/
To prevent breakage to the test runner and the links in the
documentation, let's replace those links to their original full address.

Replace git.io shortener links to full address

---

.github/workflows/test.yml
lib/App/cpm/CLI.pm
lib/App/cpm/Resolver/Cascade.pm
lib/App/cpm/Resolver/Fixed.pm
lib/App/cpm/Tutorial.pm
script/cpm
xt/lib/CLI.pm

This PR will improve resolvers for cpm.
Previously, if you specify `--resolver` option, cpm disables the default resolvers and tries to use the specified resolvers only.
In the end, this behavior only served to force the users to specify additional resolvers by themselves.
```
cpm install \
--resolver 02packages,https://example.com/darkpan \
--resolver metadb \  # most of the time, need to specify metadb resolver
Module
```
Now cpm continues using the default resolvers even if you specify `--resolver` option; so that you don't need to specify `--resolver metadb` anymore.
The first change is a breaking change. If you still want cpm not to use the default resolvers, then now you can use `--no-defualt-resolvers` option.
Now we have a handy "Fixed" resolver. If you want to pin some module's …

improve resolvers

---

lib/App/cpm/CLI.pm
script/cpm
xt/19_metafile.t

Now cpm can load initial requirements from META.json/MYMETA.json.
```shell
❯ cpm install --metafile META.json
❯ perl Makefile.PL
❯ cpm install --metafile MYMETA.json
```

Load requirements from META.json/MYMETA.json

---

lib/App/cpm/CLI.pm
lib/App/cpm/Tutorial.pm
script/cpm
xt/19_buildfile.t
xt/19_metafile.t

Now cpm tries to load initial requirements from Build.PL/Makefile.PL too.
```
❯ cd ~/src/github.com/noxxi/p5-io-socket-ssl
❯ ls
BUGS     MANIFEST       Makefile.PL  README.Win32  example  t
Changes  MANIFEST.SKIP  README       docs          lib      tls_fingerprint
❯ cpm install
Executing Makefile.PL to generate MYMETA.json and to determine requirements...
Loading requirements from MYMETA.json...
DONE install Mozilla-CA-20231213 (using prebuilt)
DONE install Net-SSLeay-1.92 (using prebuilt)
2 distributions installed.
```

try to load initial requirements from Build.PL/Makefile.PL too

---

script/cpm

Hi,
It [appears that](https://github.com/skaji/cpm/blob/1a9b27ae7b566e3dcb1154c186cce8ef4da2d481/Changes#L200-L211) `--prebuilt` cannot be used with `--test` and/or `--man-pages`. But this is not specified anywhere that I could see.
Also, it is not advertised when it happens: like "Disabling --prebuilt because of..."
This simple patch only documents the behaviour in a visible enough place :)

Disclose `--prebuilt` behaviour

---

lib/App/cpm/Master.pm
xt/14_perl_req.t

Let's say you use perl v5.30.
Previously, if module X requires modules M1, M2 and perl v5.40,
cpm will try installing M1, M2 even though the perl requirement is not satisfied.
From this PR, cpm fails fast if perl requirements are not satisfied.

fail fast if perl version requirements are not satisfied

---

lib/App/cpm/CLI.pm

It seems that #248 does not fix #246.
Actually I failed to execute cpm on macos 13.7.1 with /usr/bin/perl in github action (macos-13).
So we reverted to the previous fix #247.

dlopen Objective-C runtime before fork(2)

---

lib/App/cpm/Resolver/MetaDB.pm

Hi @skaji 👋🏼 
`cpm` is great, I love it! 😃 
```
$ cpm install --resolver=metadb Pod::Simple::HTMLLegacy@5.01 --reinstall --no-prebuilt
DONE install Pod-Simple-3.20
1 distribution installed.
$ cpm install --resolver=metacpan Pod::Simple::HTMLLegacy@5.01 --reinstall --no-prebuilt
DONE install Pod-Simple-3.45
1 distribution installed.
```
Because MetaDB history [returns several 5.01 versions](https://cpanmetadb.plackperl.org/v1.0/history/Pod::Simple::HTMLLegacy) for `Pod::Simple::HTMLLegacy`:
```
Pod::Simple::HTMLLegacy            5.01  D/DW/DWHEELER/Pod-Simple-3.20.tar.gz
Pod::Simple::HTMLLegacy            5.01  D/DW/DWHEELER/Pod-Simple-3.21.tar.gz
Pod::Simple::HTMLLegacy            5.01  D/DW/DWHEELER/Pod-Simple-3.22.tar.gz
Pod::Simple::HTMLLegacy            5.01 …
```

When pinning and using MetaDB, install freshest

---

lib/App/cpm/Resolver/02Packages.pm
lib/App/cpm/Util.pm

Currently, `cpm install --resolver 02package,index.txt,https://cpan.metacpan.org` always copies `index.txt` to `~/.perl-cpm`.
Actually this is not necessary; this PR simplifies the 02package resolver.

fix 02package resolver

---

lib/App/cpm/Worker/Installer.pm

This will reduce clone times for large repos.
If a ref is passed then the full repo is cloned.

_fetch_git: default to --depth=1 unless a ref is passed
