skaji/cpm

META.json
Makefile.PL
README.md
cpanfile
lib/Acme/CPAN/Installer.pm
lib/Acme/CPAN/Installer/Distribution.pm
lib/Acme/CPAN/Installer/Job.pm
lib/Acme/CPAN/Installer/Master.pm
lib/Acme/CPAN/Installer/Worker.pm
lib/Acme/CPAN/Installer/Worker/Installer.pm
lib/Acme/CPAN/Installer/Worker/Resolver.pm
script/cpan-installer
xt/01_installer.t
xt/02_installer.t
xt/03_resolver.t

* Now there is no assumption that requirements are statically determined! This fix #4 
* check whether packages are installed or not, fix #2 
* check version, fix #3

experimental

---

lib/App/cpm.pm
lib/App/cpm/Distribution.pm
lib/App/cpm/Master.pm
lib/App/cpm/Worker/Installer.pm
lib/App/cpm/Worker/Resolver.pm
script/cpm
xt/03_resolver.t

No more assumption that "provides" of distributions are statically determined.
Let's use http://cpanmetadb.plackperl.org/

use http://cpanmetadb.plackperl.org/

---

META.json
dist.ini
lib/App/cpm.pm
lib/App/cpm/Master.pm
lib/App/cpm/Pipes.pm
lib/App/cpm/Worker.pm

Finally I could factor out the "parallel" code to App::cpm::Pipes.
I hope I can release it a seperated module soon https://github.com/skaji/Pipes
At the same time, App::cpm::Pipes supports non-fork, which means we can use cpm in Win32.
Congrats.

use App::cpm::Pipes

---

lib/App/cpm/Resolver/Cascade.pm
lib/App/cpm/Resolver/MetaCPAN.pm
lib/App/cpm/Resolver/MetaDB.pm
lib/App/cpm/Worker/Resolver.pm

emit error log when resolving fails

---

author/fatpack.pl
lib/App/cpm/Distribution.pm
lib/App/cpm/Logger/File.pm
lib/App/cpm/Master.pm
lib/App/cpm/Worker/Installer.pm
lib/App/cpm/Worker/Installer/Menlo.pm
xt/25_static_install.t
xt/CLI.pm

opts in x_static_install

---

lib/App/cpm/Worker/Installer.pm
xt/10_basic.t

try to configure static-install, Build.PL and Makefile.PL in order

---

lib/App/cpm/Worker/Installer.pm

papix reported that:
```
❯ perl cpm install -v --home $PWD/home ExtUtils::MakeMaker@6.84
...
❯ cat /Users/skaji/src/github.com/skaji/cpm/home/build.log
2017-05-30T01:56:26,42493,ExtUtils::MakeMaker| Resolved ExtUtils::MakeMaker (== 6.84) -> http://www.cpan.org/authors/id/B/BI/BINGOS/ExtUtils-MakeMaker-6.84.tar.gz from MetaDB
2017-05-30T01:56:26,42493,ExtUtils-MakeMaker-6.84| Fetching http://www.cpan.org/authors/id/B/BI/BINGOS/ExtUtils-MakeMaker-6.84.tar.gz
2017-05-30T01:56:26,42493,ExtUtils-MakeMaker-6.84| -> OK
2017-05-30T01:56:26,42493,ExtUtils-MakeMaker-6.84| Unpacking ExtUtils-MakeMaker-6.84.tar.gz
2017-05-30T01:56:26,42493,ExtUtils-MakeMaker-6.84| -> FAIL Failed to unpack ExtUtils-MakeMaker-6.84.tar.gz: no directory
2017-05-30T01:56:26,42493,ExtUtils-MakeMaker-6.84| Fetching …
```

clean up workspace

---

.travis.yml

use cpm itself in travisci

---

lib/App/cpm.pm
lib/App/cpm/Worker/Installer.pm
lib/App/cpm/Worker/Installer/Menlo.pm
script/cpm
xt/28_timeout.t

add configure/build/test timeout options

---

lib/App/cpm.pm
lib/App/cpm/Logger/File.pm
xt/01_installer.t
xt/28_timeout.t
xt/lib/CLI.pm

With these changes, all the xt tests pass for me, under Win7+strawberry 5.22.3 as of this writing.

Fix win32 issues

---

lib/App/cpm.pm

close #31 
Try, for example,
```
> cpan-outdated -p | cpm install -g -
```

read_argv_from_stdin

---

lib/App/cpm.pm

cpanfile supports specifying requirements for optional features of an
application using "feature" blocks; the names of any features need to
be passed to Module::CPANfile's "prereqs_with" method.
Since --with options are already used for phases (runtime, configure,
test, etc.) I've used --feature. Specify multiple features as e.g.
"--feature one --feature two".

Support selecting cpanfile "features"

---

lib/App/cpm/CircularDependency.pm
lib/App/cpm/Master.pm

improve detection of circular deps

---

lib/App/cpm/Tutorial.pm

Examples git/dist syntax in cpanfile were added

---

cpm
script/cpm

Fix a minor typo for instead

---

lib/App/cpm/Master.pm
lib/App/cpm/Worker/Installer.pm
xt/34_use_unsafe_inc.t

Follow https://github.com/miyagawa/cpanminus/commit/15c8292af483b37d8aad255a4b3be54ca69fb93d, and this should fix #124.

follow Menlo; support x_use_unsafe_inc specifier in META

---

lib/App/cpm/CLI.pm
lib/App/cpm/Master.pm
lib/App/cpm/Resolver/CPANfile.pm
xt/17_cpanfile.t

introduce App::cpm::Resolver::CPANfile

---

lib/App/cpm/CLI.pm
xt/18_cpanfile_mirror.t

respect mirror in cpanfile

---

cpm
script/cpm

Warn users of new behaviour of --mirror

Address #150 by updating documentation

---

lib/App/cpm/Installer/Unpacker.pm

By default OpenBSD ships with its own version of tar(1) which is
neither bsdtar, nor GNU. This version does not use -o parameter in the
same way other two do. Instead OpenBSD tar always work as if -o is
enabled, even for root user, and has an option (-p) to disable this
behavior.
Currently this is not taken into account. On OpenBSD if executed with
-o parameter, tar prints a warning and exits with an error code.
To accommodate for that, extend tar(1) version detection to
specifically include GNU (which can also be present on OpenBSD
system), BSD, and OpenBSD versions of the tar(1) program.
There is no easy way to detect OpenBSD tar executable, as it does not
provide --version output. When OS is detected to be OpenBSD, no
additional switch is used for tar invocation, otherwise -o is kept …

Fix unpacking when using OpenBSD tar

---

lib/App/cpm/Worker/Installer.pm

See https://github.com/skaji/Command-Runner/issues/7

make sure make command exists before executing Makefile.PL

---

lib/App/cpm/Master.pm
xt/10_basic.t

treat "cpm install strict" as success

---

lib/App/cpm/CLI.pm
lib/App/cpm/Worker/Installer/Menlo.pm
xt/25_static_install.t

opts-in static install on perl 5.8, 5.10

---

lib/App/cpm/CLI.pm
lib/App/cpm/Worker/Installer/Menlo.pm
xt/25_static_install.t

Revert "opts-in static install on perl 5.8, 5.10"

---

lib/App/cpm/CLI.pm

dlopen /System/Library/Frameworks/Foundation.framework/Foundation

---

lib/App/cpm/CLI.pm

simply call Socket::inet_aton before fork(2)

---

lib/App/cpm/CLI.pm

Fix https://github.com/skaji/cpm/pull/253#issuecomment-2495935827

treat "perl" as system perl in darwin
